//
//  SearchResultResp.swift
//
//  This file is auto generated by fit.
//  Github: https://github.com/AnyOptional/fit
//
//  Copyright © 2018-present Archer. All rights reserved.
//

import YYKit

@objcMembers
class SearchResultResp: NSObject, YYModel {

	var data: DataBean?

	@objcMembers
	class DataBean: NSObject, YYModel {
		var stateCode: Int = 0
		var message: String?
		var returnData: ReturnDataBean?

		@objcMembers
		class ReturnDataBean: NSObject, YYModel {
			var comicNum: Int = 0
			var hasMore: Bool = false
			var comics: [ComicsBean]?

			@objcMembers
			class ComicsBean: NSObject, YYModel {
				var tags: [String]?
				var name: String?
				var flag: Int = 0
				var author: String?
				var comicId: Int = 0
				var updateType: Int = 0
				var descriptor: String?
				var passChapterNum: String?
				var conTag: Int = 0
				var cover: String?
                
                static func modelCustomPropertyMapper() -> [String : Any]? {
                    return ["descriptor" : "description"]
                }
			}

			var page: Int = 0
            
			static func modelContainerPropertyGenericClass() -> [String : Any]? {
    			return ["comics" : ComicsBean.self]
			}
		}

	}

	var code: Int = 0
}

