//
//  ComicRealtimeDetailResp.swift
//
//  This file is auto generated by fit.
//  Github: https://github.com/AnyOptional/fit
//
//  Copyright © 2018-present Archer. All rights reserved.
//

import YYKit

@objcMembers
class ComicRealtimeDetailResp: NSObject, YYModel {

	var data: DataBean?

	@objcMembers
	class DataBean: NSObject, YYModel {
		var returnData: ReturnDataBean?

		@objcMembers
		class ReturnDataBean: NSObject, YYModel {
			var chapter_list: [Chapter_listBean]?

			@objcMembers
			class Chapter_listBean: NSObject, YYModel {
				var zip_high_webp: String?
				var name: String?
				var size: String?
				var publish_time: Int = 0
				var is_download: Int = 0
				var countImHightArr: Int = 0
				var imHightArr: [ImHightArrBean]?

				@objcMembers
				class ImHightArrBean: NSObject, YYModel {
					var width: String?
					var height: String?
				}

				var chapterIndex: Int = 0
				var chapter_id: String?
				var buyed: String?
				var vip_images: String?
				var is_view: Int = 0
				var image_total: String?
				var is_free: Int = 0
				var read_state: Int = 0
				var crop_zip_size: String?

				static func modelContainerPropertyGenericClass() -> [String : Any]? {
    				return ["imHightArr" : ImHightArrBean.self]
				}
			}

			var comic: ComicBean?

			@objcMembers
			class ComicBean: NSObject, YYModel {
				var is_auto_buy: Int = 0
				var comment_total: String?
				var gift_total: Int = 0
				var total_tucao: Int = 0
				var is_vip_free: Bool = false
				var click_total: String?
				var year_vip_discount: Double = 0
				var is_buy_action: Int = 0
				var monthly_ticket: Int = 0
				var status: String?
				var total_ticket: Int = 0
				var month_ticket: String?
				var comic_id: String?
				var user_id: String?
				var vip_discount: Double = 0
				var favorite_total: Int = 0
				var is_free: Int = 0
				var is_vip_buy: Bool = false
			}


			static func modelContainerPropertyGenericClass() -> [String : Any]? {
    			return ["chapter_list" : Chapter_listBean.self]
			}
		}

		var message: String?
		var stateCode: Int = 0
	}

	var code: Int = 0
}

