//
//  ComicGuessLikeResp.swift
//
//  This file is auto generated by fit.
//  Github: https://github.com/AnyOptional/fit
//
//  Copyright © 2018-present Archer. All rights reserved.
//

import YYKit

@objcMembers
class ComicGuessLikeResp: NSObject, YYModel {

	var data: DataBean?

	@objcMembers
	class DataBean: NSObject, YYModel {
		var returnData: ReturnDataBean?

		@objcMembers
		class ReturnDataBean: NSObject, YYModel {
			var normal: Bool = false
			var comics: [ComicsBean]?

			@objcMembers
			class ComicsBean: NSObject, YYModel {
				var name: String?
				var cover: String?
				var short_description: String?
				var comic_id: Int = 0
			}


			static func modelContainerPropertyGenericClass() -> [String : Any]? {
    			return ["comics" : ComicsBean.self]
			}
		}

		var stateCode: Int = 0
		var message: String?
	}

	var code: Int = 0
}

