//
//  TodayRecommandResp.swift
//
//  This file is auto generated by fit.
//  Github: https://github.com/kCFNull/fit
//
//  Copyright © 2018-present Archer. All rights reserved.
//

import YYKit

@objcMembers
class TodayRecommandResp: NSObject, YYModel {

	var code: Int = 0
	var data: DataBean?

	@objcMembers
	class DataBean: NSObject, YYModel {
		var message: String?
		var returnData: ReturnDataBean?

		@objcMembers
		class ReturnDataBean: NSObject, YYModel {
			var dayDataList: [DayDataListBean]?

			@objcMembers
			class DayDataListBean: NSObject, YYModel {
				var timeStamp: String?
				var weekDay: String?
				var dayItemDataList: [DayItemDataListBean]?

				@objcMembers
				class DayItemDataListBean: NSObject, YYModel {
					var dataType: Int = 0
					var longDescription: String?
					var comicCover: String?
					var tags: [String]?
					var htmlId: Int = 0
					var comicId: Int = 0
					var type: Int = 0
					var isComicCanRead: Bool = false
					var cover: String?
					var btnColor: Int = 0
					var comicName: String?
					var shortDescription: String?
					var comicListTitle: String?
					var threadId: Int = 0
				}

				static func modelContainerPropertyGenericClass() -> [String : Any]? {
    				return ["dayItemDataList" : DayItemDataListBean.self]
				}
			}

			var last_modified: Int = 0

			static func modelContainerPropertyGenericClass() -> [String : Any]? {
    			return ["dayDataList" : DayDataListBean.self]
			}
		}

		var stateCode: Int = 0
	}

}
