//
//  TodayRecommendResp.swift
//
//  This file is auto generated by fit.
//  Github: https://github.com/kCFNull/fit
//
//  Copyright © 2018-present Archer. All rights reserved.
//

import YYKit

@objcMembers
class TodayRecommendResp: NSObject, YYModel {
    
    var msg: String?
    var data: DataBean?
    
    @objcMembers
    class DataBean: NSObject, YYModel {
        var returnData: ReturnDataBean?
        
        @objcMembers
        class ReturnDataBean: NSObject, YYModel {
            var page: Int = 0
            var isNew: Bool = false
            var hasMore: Bool = false
            var curDay: Int = 0
            var comics: [ComicsBean]?
            
            @objcMembers
            class ComicsBean: NSObject, YYModel {
                var chapterId: Int = 0
                var descriptor: String?
                var author: String?
                var uiType: Int = 0
                var comicId: Int = 0
                var title: String?
                var tagList: [TagListBean]?
                
                @objcMembers
                class TagListBean: NSObject, YYModel {
                    var tagColor: String?
                    var tagStr: String?
                }
                
                var btnColor: Int = 0
                var actionType: Int = 0
                var todayId: Int = 0
                var cover: String?
                var chapterIndex: Int = 0
                
                static func modelCustomPropertyMapper() -> [String : Any]? {
                    return ["descriptor" : "description"]
                }
                
                static func modelContainerPropertyGenericClass() -> [String : Any]? {
                    return ["tagList" : TagListBean.self]
                }
            }
            
            
            static func modelContainerPropertyGenericClass() -> [String : Any]? {
                return ["comics" : ComicsBean.self]
            }
        }
        
        var message: String?
        var stateCode: Int = 0
    }
    
    var code: Int = 0
}

